### ISSUE TITLE
Exchange usearch for vsearch

### ISSUE THREAD

**Issue by SorenKarst** [SorenKarst/longread-UMI-pipeline#12]
Anna has shown that usearch can be exchanged for vsearch here #10 .  We should make the shift to make installation more smooth and more open.

**Comment by YulinzhangSia** [comment]
Dear Soren,

Can you show me how to change the usearch path? I have entered the right path when installation, while the pipeline still transfers to the wrong version. I have checked the issue #10, but didn't find the solution. I also looked at the "/scripts/dependencies.sh", while I don't know what should be done.

Thanks
Yulin

![image](https://user-images.githubusercontent.com/51396070/87518395-d21fd000-c6b2-11ea-9149-22af13989236.png)

**Comment by SorenKarst** [comment]
Hi Yulin,

You can change the path to usearch manually by editing the "/scripts/dependencies.sh" file. The line that reads "export USEARCH=usearch" should be changed to "export USEARCH=\<path-to-usearch-executable\>". If I should do it it would look something like this:: `export USEARCH=/scratch/users/smk/software/usearch/usearch11.0.667_i86linux32`

All the best
Soren

**Comment by YulinzhangSia** [comment]
> Hi Yulin,
> 
> You can change the path to usearch manually by editing the "/scripts/dependencies.sh" file. The line that reads "export USEARCH=usearch" should be changed to "export USEARCH=<path-to-usearch-executable>". If I should do it it would look something like this:: `export USEARCH=/scratch/users/smk/software/usearch/usearch11.0.667_i86linux32`
> 
> All the best
> Soren

Hi Soren,

The problem has been solved, and thank you very much for the attentive reply!

Regards,
Yulin

**Comment by SorenKarst** [comment]
Great!

**Comment by femiliani** [comment]
I have a late follow up to this question. Replacing usearch with vsearch has not been working for me. Running the pipeline calls vsearch correctly, but I run into issues with missing commands like vsearch not having `--fastx_uniques` and instead using `--derep_fulllength` (which only works with fasta). I am quite new to bioinformatics, am I missing something obvious? 

Thanks for putting this together! 

I got the following error while running the test data for r941:

`[09:34:57 - DataIndex] No sample_registry in test_r941/raconx3_medakax1/consensus/*_consensus.hdf
Traceback (most recent call last):
  File "/home/francesco/anaconda3/envs/longread_umi/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/francesco/anaconda3/envs/longread_umi/lib/python3.6/site-packages/medaka/medaka.py", line 532, in main
    args.func(args)
  File "/home/francesco/anaconda3/envs/longread_umi/lib/python3.6/site-packages/medaka/stitch.py", line 125, in stitch
    index = medaka.datastore.DataIndex(args.inputs)
  File "/home/francesco/anaconda3/envs/longread_umi/lib/python3.6/site-packages/medaka/datastore.py", line 206, in __init__
    self.metadata = self._load_metadata()
  File "/home/francesco/anaconda3/envs/longread_umi/lib/python3.6/site-packages/medaka/datastore.py", line 244, in _load_metadata
    with DataStore(first_file) as ds:
  File "/home/francesco/anaconda3/envs/longread_umi/lib/python3.6/site-packages/medaka/datastore.py", line 39, in __init__
    self.fh = h5py.File(self.filename, self.mode)
  File "/home/francesco/anaconda3/envs/longread_umi/lib/python3.6/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/francesco/anaconda3/envs/longread_umi/lib/python3.6/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'test_r941/raconx3_medakax1/consensus/*_consensus.hdf', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
sed: can't read test_r941/raconx3_medakax1/consensus_raconx3_medakax1.fa: No such file or directory
gawk: fatal: cannot open file `test_r941/consensus_raconx3_medakax1.fa' for reading (No such file or directory)
/home/francesco/ont_dependencies/vsearch/bin/vsearch: unrecognized option '-fastx_uniques'
/home/francesco/ont_dependencies/vsearch/bin/vsearch: option '-sort' is ambiguous; possibilities: '-sortbylength' '-sortbysize'
/home/francesco/ont_dependencies/vsearch/bin/vsearch: option '-sort' is ambiguous; possibilities: '-sortbylength' '-sortbysize'
gawk: fatal: cannot open file `test_r941/variants/u_temp.uc' for reading (No such file or directory)
cat: test_r941/variants/centroids.fa: No such file or directory`
